refactor: allow all filterType options (datatable WEB)
bullcodeapps/sdk pull request #48
Opened 2023-03-14 03:45 UTC by willferreiras

2023-03-14 03:49 UTC, willferreiras commented
Linked to https://github.com/bullcodeapps/sdk/pull/48

2023-03-15 13:56 UTC, giorgiofellipe requested changes

2023-03-15 13:56 UTC, giorgiofellipe commented on packages/web/components/DataTable/index.tsx
> +        display,
```suggestion
        display = display.toString(), //hack to attend to lib types
```

2023-03-15 13:56 UTC, giorgiofellipe commented on packages/web/components/DataTable/index.tsx
> +      display = 'true',
```suggestion
      display = true,
```

2023-03-15 13:56 UTC, giorgiofellipe commented on packages/web/components/DataTable/index.tsx
> +          ...cFilterOptions,
place this spread at the top of the object, we consider all the specializations as a higher priority...

2023-03-15 13:56 UTC, giorgiofellipe commented on packages/web/components/DataTable/index.tsx
> +        ...cOptions,
place this spread at the top of the object, we consider all the specializations as a higher priority, placing at the top they won't be overridden...

2023-03-15 13:56 UTC, giorgiofellipe commented on packages/web/components/DataTable/index.tsx
> +  display?: "true" | "false" | "excluded";
```suggestion
  display?: boolean | "excluded";
```

2023-03-16 13:48 UTC, giorgiofellipe approved these changes

2023-03-16 13:48 UTC, merged